# Generated by Django 5.0.1 on 2025-11-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_customuser_is_it_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimport',
            name='status',
            field=models.CharField(blank=True, choices=[('issued', 'Issued'), ('not_issued', 'Not Issued'), ('returned', 'Returned')], help_text='Select the current status of the device.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='status',
            field=models.CharField(blank=True, choices=[('issued', 'Issued'), ('not_issued', 'Not Issued'), ('returned', 'Returned')], help_text='Select the current status of the device.', max_length=20, null=True),
        ),
    ]
