# Generated by Django 5.2.5 on 2025-11-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_customuser_is_it_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalimport',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('system_unit', 'System Unit'), ('monitor', 'Monitor'), ('tv', 'Television'), ('router', 'Router'), ('switch', 'Switch'), ('printer', 'Printer'), ('end_computing', 'End Computing'), ('other', 'Other')], default='other', help_text='Device category/type', max_length=20),
        ),
        migrations.AddField(
            model_name='import',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('system_unit', 'System Unit'), ('monitor', 'Monitor'), ('tv', 'Television'), ('router', 'Router'), ('switch', 'Switch'), ('printer', 'Printer'), ('end_computing', 'End Computing'), ('other', 'Other')], default='other', help_text='Device category/type', max_length=20),
        ),
    ]
