# Generated by Django 5.2.5 on 2025-11-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_historicalimport_category_import_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimport',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
