# Generated by Django 5.2.5 on 2025-11-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_alter_historicalimport_status_alter_import_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimport',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('system_unit', 'System Unit'), ('monitor', 'Monitor'), ('tv', 'Television'), ('router', 'Router'), ('switch', 'Switch'), ('printer', 'Printer'), ('n_computing', 'N Computing'), ('other', 'Other')], default='other', help_text='Device category/type', max_length=20),
        ),
        migrations.AlterField(
            model_name='import',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('system_unit', 'System Unit'), ('monitor', 'Monitor'), ('tv', 'Television'), ('router', 'Router'), ('switch', 'Switch'), ('printer', 'Printer'), ('n_computing', 'N Computing'), ('other', 'Other')], default='other', help_text='Device category/type', max_length=20),
        ),
    ]
