# Generated by Django 5.2.5 on 2025-12-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_alter_historicalimport_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimport',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('system_unit', 'System Unit'), ('monitor', 'Monitor'), ('tv', 'Television'), ('networking_devices', 'Networking Devices'), ('printer', 'Printer'), ('n_computing', 'N Computing'), ('projector', 'projector'), ('gadget', 'Gadget'), ('access_point', 'Access Point'), ('power_backup_equipment', 'Power & Backup Equipment'), ('other', 'Other')], default='other', help_text='Device category/type', max_length=200),
        ),
        migrations.AlterField(
            model_name='import',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('system_unit', 'System Unit'), ('monitor', 'Monitor'), ('tv', 'Television'), ('networking_devices', 'Networking Devices'), ('printer', 'Printer'), ('n_computing', 'N Computing'), ('projector', 'projector'), ('gadget', 'Gadget'), ('access_point', 'Access Point'), ('power_backup_equipment', 'Power & Backup Equipment'), ('other', 'Other')], default='other', help_text='Device category/type', max_length=200),
        ),
    ]
