# Generated by Django 5.2.5 on 2025-12-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplantask',
            name='reschedule_reason',
            field=models.TextField(blank=True, help_text='Reason for rescheduling this task (required when rescheduling)', null=True),
        ),
    ]
