# Generated by Django 5.2.5 on 2025-11-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_operations', '0008_alter_incidentreport_date_of_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed'), ('Resolved', 'Resolved')], default='Open', max_length=50),
        ),
    ]
