# Generated by Django 5.2.5 on 2025-11-20 06:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_alter_historicalimport_category_and_more'),
        ('it_operations', '0009_incidentreport_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplancomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workplancomment',
            name='work_plan',
        ),
        migrations.RemoveField(
            model_name='workplantaskcomment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='workplantaskcomment',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='workplan',
            options={'ordering': ['-week_start_date'], 'verbose_name': 'Work Plan'},
        ),
        migrations.AlterModelOptions(
            name='workplantask',
            options={'ordering': ['date', 'created_at'], 'verbose_name': 'Work Plan Task'},
        ),
        migrations.RemoveField(
            model_name='workplantask',
            name='day',
        ),
        migrations.RemoveField(
            model_name='workplantask',
            name='human_resources',
        ),
        migrations.RemoveField(
            model_name='workplantask',
            name='items_needed',
        ),
        migrations.RemoveField(
            model_name='workplantask',
            name='status_updated_by',
        ),
        migrations.RemoveField(
            model_name='workplantask',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='workplantask',
            name='collaborators',
            field=models.ManyToManyField(blank=True, help_text='Internal IT Staff or Trainers working on this specific task', related_name='collaborating_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workplantask',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Specific calendar date for this task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workplantask',
            name='other_parties',
            field=models.TextField(blank=True, help_text='External vendors, non-IT staff, or other stakeholders involved', null=True),
        ),
        migrations.AddField(
            model_name='workplantask',
            name='resources_needed',
            field=models.TextField(blank=True, help_text='Hardware, Software, Transport, Budget, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='workplan',
            name='week_end_date',
            field=models.DateField(help_text='The Saturday date of this work week'),
        ),
        migrations.AlterField(
            model_name='workplan',
            name='week_start_date',
            field=models.DateField(help_text='The Monday date of this work week'),
        ),
        migrations.AlterField(
            model_name='workplantask',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.centre'),
        ),
        migrations.AlterField(
            model_name='workplantask',
            name='comments',
            field=models.TextField(blank=True, help_text='User remarks or justification', null=True),
        ),
        migrations.AlterField(
            model_name='workplantask',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.department'),
        ),
        migrations.AlterField(
            model_name='workplantask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Rescheduled', 'Rescheduled'), ('Not Done', 'Not Done')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='workplantask',
            name='target',
            field=models.CharField(blank=True, help_text="Measurable outcome (e.g., '50 PCs serviced')", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='workplantask',
            name='task_name',
            field=models.CharField(help_text='What is the specific task?', max_length=255),
        ),
        migrations.DeleteModel(
            name='WorkPlanActivity',
        ),
        migrations.DeleteModel(
            name='WorkPlanComment',
        ),
        migrations.DeleteModel(
            name='WorkPlanTaskComment',
        ),
    ]
