# Generated by Django 5.2.5 on 2025-11-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_operations', '0010_remove_workplancomment_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='workplantask',
            name='is_leave',
            field=models.BooleanField(default=False, help_text='Is the staff member on leave this day?'),
        ),
    ]
