# Generated by Django 5.2.5 on 2025-12-16 12:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_alter_historicalimport_category_and_more'),
        ('it_operations', '0011_publicholiday_workplantask_is_leave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPlanActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('activity', models.TextField(help_text='Description of the activity/task')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='WorkPlanComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkPlanTaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PublicHoliday',
        ),
        migrations.AlterModelOptions(
            name='workplan',
            options={'ordering': ['-week_start_date'], 'verbose_name': 'Work Plan', 'verbose_name_plural': 'Work Plans'},
        ),
        migrations.AlterModelOptions(
            name='workplantask',
            options={'ordering': ['day', 'created_at'], 'verbose_name': 'Work Plan Task', 'verbose_name_plural': 'Work Plan Tasks'},
        ),
        migrations.RemoveField(
            model_name='workplantask',
            name='collaborators',
        ),
        migrations.RemoveField(
            model_name='workplantask',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workplantask',
            name='is_leave',
        ),
        migrations.RemoveField(
            model_name='workplantask',
            name='other_parties',
        ),
        migrations.RemoveField(
            model_name='workplantask',
            name='resources_needed',
        ),
        migrations.AddField(
            model_name='workplantask',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workplantask',
            name='human_resources',
            field=models.ManyToManyField(blank=True, help_text='Assigned staff members', related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workplantask',
            name='items_needed',
            field=models.CharField(blank=True, help_text='Items/resources needed (e.g., Portal, Help desk)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workplantask',
            name='status_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_status_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workplantask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workplan',
            name='week_end_date',
            field=models.DateField(help_text='Saturday of the week (Sunday excluded)'),
        ),
        migrations.AlterField(
            model_name='workplan',
            name='week_start_date',
            field=models.DateField(help_text='Monday of the week'),
        ),
        migrations.AlterField(
            model_name='workplantask',
            name='centre',
            field=models.ForeignKey(blank=True, help_text='Centre/Location (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.centre'),
        ),
        migrations.AlterField(
            model_name='workplantask',
            name='comments',
            field=models.TextField(blank=True, help_text='Additional comments/details about the task', null=True),
        ),
        migrations.AlterField(
            model_name='workplantask',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.department'),
        ),
        migrations.AlterField(
            model_name='workplantask',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Not Completed', 'Not Completed'), ('Not Done', 'Not Done')], default='Not Done', max_length=20),
        ),
        migrations.AlterField(
            model_name='workplantask',
            name='target',
            field=models.CharField(blank=True, help_text='Target/Desired outcome', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='workplantask',
            name='task_name',
            field=models.CharField(help_text='Task name/title', max_length=255),
        ),
        migrations.AddField(
            model_name='workplanactivity',
            name='work_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='it_operations.workplan'),
        ),
        migrations.AddField(
            model_name='workplancomment',
            name='work_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='it_operations.workplan'),
        ),
        migrations.AddField(
            model_name='workplantaskcomment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to='it_operations.workplantask'),
        ),
        migrations.AddField(
            model_name='workplantaskcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
