# Generated by Django 5.2.2 on 2025-08-28 11:09

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppm', '0002_historicalppmtask_ppmactivity_ppmperiod_ppmtask_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ppmperiod',
            options={},
        ),
        migrations.RenameField(
            model_name='ppmtask',
            old_name='issues',
            new_name='remarks',
        ),
        migrations.AlterUniqueTogether(
            name='ppmtask',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ppmtask',
            name='activities',
            field=models.ManyToManyField(to='ppm.ppmactivity'),
        ),
        migrations.AddField(
            model_name='ppmtask',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppmtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 28, 11, 9, 31, 364120, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppmtask',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ppmtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ppmactivity',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ppmperiod',
            name='activities',
            field=models.ManyToManyField(blank=True, to='ppm.ppmactivity'),
        ),
        migrations.AlterField(
            model_name='ppmperiod',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ppmtask',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppm.ppmperiod'),
        ),
        migrations.DeleteModel(
            name='HistoricalPPMTask',
        ),
        migrations.RemoveField(
            model_name='ppmtask',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='ppmtask',
            name='done_at',
        ),
        migrations.RemoveField(
            model_name='ppmtask',
            name='done_by',
        ),
        migrations.RemoveField(
            model_name='ppmtask',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='ppmtask',
            name='recommendations',
        ),
    ]
